# Generated by Django 3.1.1 on 2020-10-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_marca_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('idSubcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.subcategoria')),
            ],
        ),
    ]
