# Generated by Django 3.1.1 on 2020-10-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_talla_tallaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='subCategorias',
            field=models.ManyToManyField(related_name='subCategorias', to='productos.Subcategoria'),
        ),
        migrations.DeleteModel(
            name='SubcategoriaProducto',
        ),
    ]
