# Generated by Django 3.1.1 on 2020-10-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20201016_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='subCategorias',
            field=models.ManyToManyField(related_name='subCategorias', related_query_name='productos', to='productos.Subcategoria'),
        ),
    ]
